name: daily-run

on:
  schedule:
    # Runs every day at 11:00 UTC (which corresponds to 12:00 Europe/Amsterdam during CET).
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LIKE_THRESHOLD: ${{ secrets.LIKE_THRESHOLD }} # optional
        run: |
          python bot.py
